# Continuous Deployment Workflow for Stage
name: deploy-to-canary
run-name: Continuous deployment triggered by ${{ github.event_name }}

on:
  # Runs on pushes targeting the default branch
  repository_dispatch:
    types: [deploy]

jobs:

  # Build static site using Reveal-MD
  build-canary:
    name: Build CAN
    if: ${{ !github.event.client_payload.paused }}
    uses: dr3dr3/devops-via-preso/.github/workflows/reuse-build-revealmd.yml@main
    with: 
      target-ref: ${{ github.event.client_payload.target_ref }}
      deploy-target: 'can'
    secrets: inherit

  # Deploy to GitHub Pages on the Stage Repo
  deploy-to-github-pages:
    name: Deploy GHP(CAN)
    needs: build-canary
    uses: dr3dr3/devops-via-preso/.github/workflows/reuse-deploy-github-pages.yml@main
    permissions:
      contents: read
      pages: write
      id-token: write
    with:
      target-ref: ${{ github.event.client_payload.target_ref }}
      deploy-target: 'can'
    secrets: inherit