name: DEPLOY-TO-CANARY
run-name: Continuous Deployment for Canary Environment

on:
  # Runs on pushes targeting the default branch
  repository_dispatch:
    types: [deploy]

jobs: 

  # Continuous delivery workflow in 'ss-pipeline' repo
  continuous-delivery:
    name: CD
    uses: dr3dr3/ss-pipeline/.github/workflows/continuous-delivery.yml@main
    with: 
      from-soln: ${{ github.event.client_payload.from_soln }}
      target-ref: ${{ github.event.client_payload.target_ref }}
      target-deploy: 'can'
    permissions:
      contents: read
      pages: write
      id-token: write
    secrets: inherit

  ### Add testing specific for CAN (pvt, etc)

  # Given successful testing then update the build for this environment in GitOps Config
  build-config:
    name: Update Build Config
    needs: [continuous-delivery]
    uses: dr3dr3/ss-pipeline/.github/workflows/gitops-update.yml@main
    with:
      config-item: '.deploy.revealmd.build.can'
      config-value: ${{ github.event.client_payload.target_ref }}
    secrets: inherit

  # No deploy to Production triggered. Run on schedule via cd-scheduler.yml